name: "Changelog CLI"
description: "Create a change log based of git commit history"
inputs:
  service-name:
    description: "Name of the service being released"
    required: true
  github-release:
    description: "Create a jira release? (True or false)"
    required: true
  github-token:
    description: "Github token used for generating releases"
    required: true
  jira-app-name:
    description: "Name of the Jira app used for generating Jira issue links"
    required: false
  output:
    description: "Output mode (console,slack)"
    required: true
  slack-token:
    description: "Slack App API Token used for publishing changelog"
    required: true
  slack-channel:
    description: "Which slack channel should this be published to"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Download changelog cli
      run: |
        curl -L -o changelog-cli https://github.com/monta-app/changelog-cli/releases/download/v1.0.2/changelog-cli
        chmod +x ./changelog-cli
      shell: bash
    - name: Run changelog cli
      env:
        CHANGELOG_SERVICE_NAME: ${{ inputs.service-name }}
        CHANGELOG_GITHUB_RELEASE: ${{ inputs.github-release }}
        CHANGELOG_GITHUB_TOKEN: ${{ inputs.github-token }}
        CHANGELOG_JIRA_APP_NAME: ${{ inputs.jira-app-name }}
        CHANGELOG_OUTPUT: ${{ inputs.output }}
        CHANGELOG_SLACK_TOKEN: ${{ inputs.slack-token }}
        CHANGELOG_SLACK_CHANNEL_NAME: ${{ inputs.slack-channel }}
      run: ./changelog-cli
      shell: bash
